### ISSUE TITLE
Verificar la viabilidad de incorporar el servicio de busca rápida de términos DeCS como nuevo metodo en el API

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/decs-api#13]
Estimada @yaznagv,

Estoy creando este issue para documentar los avanzos en el analisis deste tema. En los proximos dias voy añadir en los comentarios detalles adicionales para ayudar a entender este servicio.

El DeCS tiene un servicio separado denominado DeCSQuickTerm (https://srv.bvsalud.org/decsQuickTerm/) que permite la busca rápida de los descriptores. 

Este servicio es utilizado en el autocomplete de la opción "Localizar descriptor de asunto" de la búsqueda BVS:

https://pesquisa.bvsalud.org/portal/decs-locator/?lang=es

Cuando posible, le agradezco analisar los codigos fuentes para verificar si es posible agregar este servicio como um metodo nuevo la nueva API .

Repositório en GitHub del servicio actual:

https://github.com/bireme/decsquickterm/

Principal archivo del servicio:

https://github.com/bireme/decsquickterm/blob/master/src/java/org/bireme/decsterm/servlet/Search.java

**Comment by yaznagv** [comment]
### Requerimientos y dudas sobre la busqueda rapida a partir del analisis del codigo del servicio actual

**Api búsqueda rápida DeCS**

Parámetros:
- query
- count (por defecto = 100)
- lang 

Respuesta:

- total de resultados
- Lista de términos con:
> -  tree_id
> -  term


Búsqueda:
- En todos los índices (se refiere a índices en todos los idiomas)
- Operador AND para interconectar las palabras.
- 1ra búsqueda: 2 elementos, para obtener los 2 de mayor relevancia y el total de resultados   
- 2da búsqueda: por orden alfabético, completar resultados hasta llegar como máximo a count 
- De cada elemento (hit) se obtiene termino y tree_id

Dudas:

- Búsqueda de:
> - Términos autorizados, sinónimos, históricos
> - Asociados a descriptores y también calificadores
- Se utiliza “term_words”, = palabra a palabra?
- Se utiliza StandardLatinAnalyzer
Ver si coincide con los analizadores con los que se han indexado los términos de descriptores y calificadores. Sino agregar este analizador a la indexación en ES
- Parámetro lang no se utiliza, mantenerlo en la API?

**Comment by yaznagv** [comment]
Hola Vinicius:

Agregue al issue un comentario con lo que entendi del codigo del servicio
DeCSQuickTerm y algunas dudas

saludos Yazna

Vinicius de Andrade ***@***.***> escribió:

> Estimada @yaznagv,
>
> Estoy creando este issue para documentar los avanzos en el analisis  
> deste tema. En los proximos dias voy añadir en los comentarios  
> detalles adicionales para ayudar a entender este servicio.
>
> El DeCS tiene un servicio separado denominado DeCSQuickTerm  
> (https://srv.bvsalud.org/decsQuickTerm/) que permite la busca rápida  
> de los descriptores.
>
> Este servicio es utilizado en el autocomplete de la opción  
> "Localizar descriptor de asunto" de la búsqueda BVS:
>
> https://pesquisa.bvsalud.org/portal/decs-locator/?lang=es
>
> Cuando posible, le agradezco analisar los codigos fuentes para  
> verificar si es posible agregar este servicio como um metodo nuevo  
> la nueva API .
>
> Repositório en GitHub del servicio actual:
>
> https://github.com/bireme/decsquickterm/
>
> Principal archivo del servicio:
>
> https://github.com/bireme/decsquickterm/blob/master/src/java/org/bireme/decsterm/servlet/Search.java
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/bireme/decs-api/issues/13
> You are receiving this because you were assigned.
>
> Message ID: ***@***.***>




--
Este mensaje le ha llegado mediante el servicio de correo electronico que ofrece Infomed para respaldar el cumplimiento de las misiones del Sistema Nacional de Salud. La persona que envia este correo asume el compromiso de usar el servicio a tales fines y cumplir con las regulaciones establecidas

Infomed: http://www.sld.cu/

**Comment by viniciusandrade** [comment]
Hola @yaznagv,

Gracias por tu análisis inicial del servicio.

Acerca de sus dudas:
- La búsqueda es hecha solamente en los terminos autorizados y sinónimos, este es un ejemplo del XML que es utilizado por el script java para crear el indice
```
    <term mfn="14">
          <descriptor>Anomalías Congénitas</descriptor>
          <tree_id>C16.131</tree_id>
          <synonym_list>
               <synonym>Anomalía Congénita</synonym>
               <synonym>Anomalías fetales</synonym>
               <synonym>Defectos Congénitos</synonym>
               <synonym>Deformidades</synonym>
               <synonym>Malformaciones</synonym>
               <synonym>Malformaciones Congénitas</synonym>
               <synonym>Malformaciones Fetales</synonym>
          </synonym_list>
     </term>
```

- Se utiliza “term_words”, = palabra a palabra?  
-- Sí, term_words debe ser indizado palabra a palabra

- Se utiliza StandardLatinAnalyzer
-- El codigo de StandardLatinAnalyzer no es mas compatible con las nuevas versiones de Lucene, creo que si puede utilizar WhitespaceTokenizerFactory con el filtro ASCIIFoldingFilterFactory

- Parámetro lang no se utiliza, mantenerlo en la API?
-- No és necesario.

**Comment by yaznagv** [comment]
Hola Vinicius:

He agregado la version inicial del api de Busqueda rapida.
Falta:
- definir como ordenar los resultados y si se necesita paginacion 
- definir si se necesita autocompletado

**Comment by yaznagv** [comment]
Hola Vinicius:

Agregue al api parametro count para limitar ctdad de resultados

**Comment by viniciusandrade** [comment]
Hola @yaznagv,

Gracias por el pull request. Estoy intentando incorporar el codigo en nuestro ambiente de pruebas pero no logro hacer uso del nuevo servicio, podrias me ayudar a identificar el problema?

1. Ejecuté el comando para rebuild del indice elasticsearch

    python manage.py search_index --rebuild -f --models thesaurus

2. Estoy probando con la url de ejemplo abajo:

    https://decs-api.teste.bvsalud.org/api/thesaurus/term/?quick=saude

Gracias
Vinicius

**Comment by yaznagv** [comment]
Vinicius:

la url seria la sgte:

https://decs-api.teste.bvsalud.org/api/thesaurus/quickterm/?query=saude

ya la probe y funciono

chao

Vinicius de Andrade ***@***.***> escribió:

> Hola @yaznagv,
>
> Gracias por el pull request. Estoy intentando incorporar el codigo  
> en nuestro ambiente de pruebas pero no logro hacer uso del nuevo  
> servicio, podrias me ayudar a identificar el problema?
>
> 1. Ejecuté el comando para rebuild del indice elasticsearch
>
>     python manage.py search_index --rebuild -f --models thesaurus
>
> 2. Estoy probando con la url de ejemplo abajo:
>
>     https://decs-api.teste.bvsalud.org/api/thesaurus/term/?quick=saude
>
> Gracias
> Vinicius
>
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/bireme/decs-api/issues/13#issuecomment-1420933342
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>




--
Este mensaje le ha llegado mediante el servicio de correo electronico que ofrece Infomed para respaldar el cumplimiento de las misiones del Sistema Nacional de Salud. La persona que envia este correo asume el compromiso de usar el servicio a tales fines y cumplir con las regulaciones establecidas

Infomed: http://www.sld.cu/

**Comment by viniciusandrade** [comment]
Perfecto @yaznagv, muchas gracias por apuntar la correcta url para el servicio.

Un punto que es mucho importante para los usuarios del servicio (bibliotecarios para indización) es la orden del resultado.

Seria posible intentar aplicar un sort por relevancia (score) y alfabetico para verificar si el retorno si acerca un poco mas del resultado actual?

Ejemplo:
https://srv.bvsalud.org/decsQuickTerm/search?lang=pt&query=enfermagem

https://decs-api.teste.bvsalud.org/api/thesaurus/quickterm/?query=enfermagem&count=100

Gracias
Vinicius

**Comment by yaznagv** [comment]
Ok vinicius, cuando lo tenga lo subo al github

quedamos en que lang no iba a ser un parametro y lo veo aqui:
https://srv.bvsalud.org/decsQuickTerm/search?lang=pt&query=enfermagem

hay que dar la posibilidad de filtrar los resultados por idioma?

saludos yazna

Vinicius de Andrade ***@***.***> escribió:

> Perfecto @yaznagv, muchas gracias por apuntar la correcta url para  
> el servicio.
>
> Un punto que es mucho importante para los usuarios del servicio  
> (bibliotecarios para indización) es la orden del resultado.
>
> Seria posible intentar aplicar un sort por relevancia (score) y  
> alfabetico para verificar si el retorno si acerca un poco mas del  
> resultado actual?
>
> Ejemplo:
> https://srv.bvsalud.org/decsQuickTerm/search?lang=pt&query=enfermagem
>
> https://decs-api.teste.bvsalud.org/api/thesaurus/quickterm/?query=enfermagem&count=100
>
> Gracias
> Vinicius
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/bireme/decs-api/issues/13#issuecomment-1421575998
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>




--
Este mensaje le ha llegado mediante el servicio de correo electronico que ofrece Infomed para respaldar el cumplimiento de las misiones del Sistema Nacional de Salud. La persona que envia este correo asume el compromiso de usar el servicio a tales fines y cumplir con las regulaciones establecidas

Infomed: http://www.sld.cu/

**Comment by yaznagv** [comment]
Vinicius:

Hice alguna pruebas con lang y sin lang y los resultados son los  
mismos, realmente nunca filtra por idioma

El API de busqueda rapida no devuelve resultados repetidos, por ejemplo

https://srv.bvsalud.org/decsQuickTerm/search?query=enferma
<DeCSTermService version="0.1.0">
<Result total="4" count="100">
<item id="HP1.007.262" term="Enferma"/>
<item id="HP1.007.262" term="Enferma"/>
<item id="HP1.007.262" term="Enferma"/>
<item id="HP1.007.262" term="Enferma"/>
<item id="HP1.007.262" term="Persona Enferma"/>
<item id="HP1.007.262" term="Pessoa Enferma"/>
</Result>
</DeCSTermService>

pero
https://decs-api.teste.bvsalud.org/api/thesaurus/quickterm/?query=enferma&count=100

<DeCSTermService version="1.0">
<Result count="100" total="5">
<item id="HP1.007.262" term="Enferma"/>
<item id="HP1.007.262" term="Persona Enferma"/>
<item id="HP1.007.262" term="Pessoa Enferma"/>
<item id="HP1.007.262" term="enferma"/>
<item id="HP1.007.262" term="persona enferma"/>
</Result>
</DeCSTermService>

los dos ultimos (en minuscula son para ES-es, si mal no recuerdo),  
pero no repite Enferma como en el servicio anterior

Esto del orden era una de las cosas por definir. Lo que me parecio en  
el codigo del servicio anterior fue que se obtienen los dos resultados  
mas relevantes y luego se obtiene listado por orden alfabetico. Es asi?

saludos yazna



***@***.*** escribió:

> Ok vinicius, cuando lo tenga lo subo al github
>
> quedamos en que lang no iba a ser un parametro y lo veo aqui:
> https://srv.bvsalud.org/decsQuickTerm/search?lang=pt&query=enfermagem
>
> hay que dar la posibilidad de filtrar los resultados por idioma?
>
> saludos yazna
>
> Vinicius de Andrade ***@***.***> escribió:
>
>> Perfecto @yaznagv, muchas gracias por apuntar la correcta url para  
>> el servicio.
>>
>> Un punto que es mucho importante para los usuarios del servicio  
>> (bibliotecarios para indización) es la orden del resultado.
>>
>> Seria posible intentar aplicar un sort por relevancia (score) y  
>> alfabetico para verificar si el retorno si acerca un poco mas del  
>> resultado actual?
>>
>> Ejemplo:
>> https://srv.bvsalud.org/decsQuickTerm/search?lang=pt&query=enfermagem
>>
>> https://decs-api.teste.bvsalud.org/api/thesaurus/quickterm/?query=enfermagem&count=100
>>
>> Gracias
>> Vinicius
>>
>> --
>> Reply to this email directly or view it on GitHub:
>> https://github.com/bireme/decs-api/issues/13#issuecomment-1421575998
>> You are receiving this because you were mentioned.
>>
>> Message ID: ***@***.***>




--
Este mensaje le ha llegado mediante el servicio de correo electronico que ofrece Infomed para respaldar el cumplimiento de las misiones del Sistema Nacional de Salud. La persona que envia este correo asume el compromiso de usar el servicio a tales fines y cumplir con las regulaciones establecidas

Infomed: http://www.sld.cu/

**Comment by viniciusandrade** [comment]
@yaznagv 

Así es ... el servicio actual no filtra por idioma, simpre retorna los descriptores en todos los idiomas. No es necesario traer el termo repetido multiplas vezes si es escrito de la misma forma en otro idioma.

Sí fuera simples implementar la regla de cuando no es informado el parametro lang trae todos los idiomas y si fuera informado el parametro lang filtro por idioma OK, si no es simple dejamos desta misma forma retornando simpre todo.

Acerca del orden del resultado su analisis esta correcta. 
Como prueba podria intentar aplicar um sort con el score y alfabetico del term, algo asi:
```
sort" : [
    "_score",
    { "term" : {"order" : "asc"}},
],
```
Para verificar si la orden sera parecido con el servicio actual.

Gracias.

**Comment by yaznagv** [comment]
Hola Vinicius:

Creo que lo del idioma se puede implementar sin mucha dificultad,  
reviso y me documento sobre las opciones de ordenamiento para ver como  
implementarlas

saludos yazna



Vinicius de Andrade ***@***.***> escribió:

> @yaznagv
>
> Así es ... el servicio actual no filtra por idioma, simpre retorna  
> los descriptores en todos los idiomas. No es necesario traer el  
> termo repetido multiplas vezes si es escrito de la misma forma en  
> otro idioma.
>
> Sí fuera simples implementar la regla de cuando no es informado el  
> parametro lang trae todos los idiomas y si fuera informado el  
> parametro lang filtro por idioma OK, si no es simple dejamos desta  
> misma forma retornando simpre todo.
>
> Acerca del orden del resultado su analisis esta correcta.
> Como prueba podria intentar aplicar um sort con el score y  
> alfabetico del term, algo asi:
> ```
> sort" : [
>     "_score",
>     { "term" : {"order" : "asc"}},
> ],
> ```
> Para verificar si la orden sera parecido con el servicio actual.
>
> Gracias.
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/bireme/decs-api/issues/13#issuecomment-1423155625
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>




--
Este mensaje le ha llegado mediante el servicio de correo electronico que ofrece Infomed para respaldar el cumplimiento de las misiones del Sistema Nacional de Salud. La persona que envia este correo asume el compromiso de usar el servicio a tales fines y cumplir con las regulaciones establecidas

Infomed: http://www.sld.cu/

**Comment by viniciusandrade** [comment]
Hola Yazna,

Perfecto, muchas gracias. Quedo atento a sus ajustes.

Abrazos
Vinicius

**Comment by yaznagv** [comment]
Hola Vinicius:

Ya estan en el github las modificaciones al API de busqueda rapida,  
son los dos ultimos commit:

-Agregado lang como parametro del api
-Orden de resultados en api de busqueda rapida

Para el ordenamiento alfabetico se modificaron indices, por lo que se  
necesita hacer rebuild, los detalles estan en la descripcion de los  
commit

Los resultados del servicio anterior y del API estan bastante  
parecidos, solo que los de calificadores salen al final, no se si es  
pq son en minusculas

saludos Yazna




Vinicius de Andrade ***@***.***> escribió:

> Hola Yazna,
>
> Perfecto, muchas gracias. Quedo atento a sus ajustes.
>
> Abrazos
> Vinicius
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/bireme/decs-api/issues/13#issuecomment-1424571037
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>




--
Este mensaje le ha llegado mediante el servicio de correo electronico que ofrece Infomed para respaldar el cumplimiento de las misiones del Sistema Nacional de Salud. La persona que envia este correo asume el compromiso de usar el servicio a tales fines y cumplir con las regulaciones establecidas

Infomed: http://www.sld.cu/

**Comment by yaznagv** [comment]
Vinicius:

He revisado lo de mayusculas y minusculas, y el orden alfabetico en ES  
es case sensitive. He encontrado algunas soluciones las pruebo y  
actualizo en github

saludos Yazna


Vinicius de Andrade ***@***.***> escribió:

> Hola Yazna,
>
> Perfecto, muchas gracias. Quedo atento a sus ajustes.
>
> Abrazos
> Vinicius
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/bireme/decs-api/issues/13#issuecomment-1424571037
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>




--
Este mensaje le ha llegado mediante el servicio de correo electronico que ofrece Infomed para respaldar el cumplimiento de las misiones del Sistema Nacional de Salud. La persona que envia este correo asume el compromiso de usar el servicio a tales fines y cumplir con las regulaciones establecidas

Infomed: http://www.sld.cu/

**Comment by yaznagv** [comment]
Vinicius:

Ya esta resuelto el orden alfabetico case insensitive, ver ultimo  
commit, igual hay que hacer rebuild de los dos indices de terminos.

chao Yazna


--
Este mensaje le ha llegado mediante el servicio de correo electronico que ofrece Infomed para respaldar el cumplimiento de las misiones del Sistema Nacional de Salud. La persona que envia este correo asume el compromiso de usar el servicio a tales fines y cumplir con las regulaciones establecidas

Infomed: http://www.sld.cu/

**Comment by viniciusandrade** [comment]
Gracias Yazna,

Ya esta actualizado en el ambiente de pruebas https://decs-api.teste.bvsalud.org/api/thesaurus/
