### ISSUE TITLE
Revisar el retorno de las consultas por words y bool

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/decs-api#15]
Hola @yaznagv,

El equipo de contenidos de DeCS esta haciendo las validaciones de la nueva version de API y informaran que el resultado de las búsquedas no deberian estar considerando los ancestors de un descriptor.

Ejemplo: 

Para la búsqueda por **blood** la nueva API están retornando un total de 285 resultados que incluen los terminos: 

Epigastric Arteries
Sphygmomanometers
Hypovolemia
Defensins
etc 
...

Pero estes descriptores no estan presente en el resultado original de la API (que retorna un total de 159):

https://decs.bvsalud.org/cgi-bin/mx/cgi=@vmx/decs?words=blood&lang=en

Estes ejemplos arriba deben ser todos de un mesmo tipo (me parece que son ancestors) y no deberian ser incluidos en el resultado. Me explico?

Es posible revisar el codigo para restringir el alcance de la búsqueda?

Gracias

**Comment by yaznagv** [comment]
Hola Vinicius:

Estos resultados no es que este buscando en los ancestors, sino en los  
terminos historicos. Por ejemplo:

Epigastric Arteries

en thesaurus_termlistdesc

   id: 156404
   term_string: Epigastric Arteries
   concept_preferred_term: Y
   record_preferred_term: Y
   identifier_concept_id: 40409

en thesaurus_identifierconceptlistdesc
   id: 40409
   identifier_id: 19682   (este es el identificador del descriptor  
cuyo term_string: Epigastric Arteries)

en thesaurus_previousindexinglistdesc (que se indexa para terminos  
historicos), es donde se encuentra la palabra blood

   id:18024
   previous_indexing: Abdominal Muscles/blood supply (1966-1995)
   identifier_id: 19682

puedo probar, quitar el indice de terminos historicos de la busqueda  
para volver a comparar resultados

saludos yazna






Vinicius de Andrade ***@***.***> escribió:

> Hola @yaznagv,
>
> El equipo de contenidos de DeCS esta haciendo las validaciones de la  
> nueva version de API y informaran que el resultado de las búsquedas  
> no deberian estar considerando los ancestors de un descriptor.
>
> Ejemplo:
>
> Para la búsqueda por **blood** la nueva API están retornando un  
> total de 285 resultados que incluen los terminos:
>
> Epigastric Arteries
> Sphygmomanometers
> Hypovolemia
> Defensins
> etc
> ...
>
> Pero estes descriptores no estan presente en el resultado original  
> de la API (que retorna un total de 159):
>
> ***@***.***/decs?words=blood&lang=en
>
> Estes ejemplos arriba deben ser todos de un mesmo tipo (me parece  
> que son ancestors) y no deberian ser incluidos en el resultado. Me  
> explico?
>
> Es posible revisar el codigo para restringir el alcance de la búsqueda?
>
> Gracias
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/bireme/decs-api/issues/15
> You are receiving this because you were assigned.
>
> Message ID: ***@***.***>




--
Este mensaje le ha llegado mediante el servicio de correo electronico que ofrece Infomed para respaldar el cumplimiento de las misiones del Sistema Nacional de Salud. La persona que envia este correo asume el compromiso de usar el servicio a tales fines y cumplir con las regulaciones establecidas

Infomed: http://www.sld.cu/

**Comment by yaznagv** [comment]
Vinicius:

Probe local sin indice previous_term y devuelve 160 resultados, en  
todos aparece
blood en termino preferido o en sinonimos. Aqui la diferencia (1  
registro) puede estar en actualizaciones que se han hecho al decs.

puedo subirlo asi para que continuen las pruebas,

saludos yazna

Vinicius de Andrade ***@***.***> escribió:

> Hola @yaznagv,
>
> El equipo de contenidos de DeCS esta haciendo las validaciones de la  
> nueva version de API y informaran que el resultado de las búsquedas  
> no deberian estar considerando los ancestors de un descriptor.
>
> Ejemplo:
>
> Para la búsqueda por **blood** la nueva API están retornando un  
> total de 285 resultados que incluen los terminos:
>
> Epigastric Arteries
> Sphygmomanometers
> Hypovolemia
> Defensins
> etc
> ...
>
> Pero estes descriptores no estan presente en el resultado original  
> de la API (que retorna un total de 159):
>
> ***@***.***/decs?words=blood&lang=en
>
> Estes ejemplos arriba deben ser todos de un mesmo tipo (me parece  
> que son ancestors) y no deberian ser incluidos en el resultado. Me  
> explico?
>
> Es posible revisar el codigo para restringir el alcance de la búsqueda?
>
> Gracias
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/bireme/decs-api/issues/15
> You are receiving this because you were assigned.
>
> Message ID: ***@***.***>




--
Este mensaje le ha llegado mediante el servicio de correo electronico que ofrece Infomed para respaldar el cumplimiento de las misiones del Sistema Nacional de Salud. La persona que envia este correo asume el compromiso de usar el servicio a tales fines y cumplir con las regulaciones establecidas

Infomed: http://www.sld.cu/

**Comment by viniciusandrade** [comment]
Hola Yazna,

Perfecto, gracias por su analisis que si trataban de terminos historicos. 

Me quedo atento a su pull request para actualizar nuestro ambiente.

Gracias.

**Comment by yaznagv** [comment]
Hola Vinicius:

Ya esta en el repositorio

saludos yazna



Vinicius de Andrade ***@***.***> escribió:

> Hola Yazna,
>
> Perfecto, gracias por su analisis que si trataban de terminos historicos.
>
> Me quedo atento a su pull request para actualizar nuestro ambiente.
>
> Gracias.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/bireme/decs-api/issues/15#issuecomment-1448089553
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>




--
Este mensaje le ha llegado mediante el servicio de correo electronico que ofrece Infomed para respaldar el cumplimiento de las misiones del Sistema Nacional de Salud. La persona que envia este correo asume el compromiso de usar el servicio a tales fines y cumplir con las regulaciones establecidas

Infomed: http://www.sld.cu/

**Comment by viniciusandrade** [comment]
Gracias Yazna,

Ya actualizé nuestro ambiente y el resultado y ahora creo que el resultado esta perfecto.

Voy cerrar este issue y cualquier comentario adicional del equipo de contenido la aviso.

Gracias

**Comment by yaznagv** [comment]
OK, perfecto


Vinicius de Andrade ***@***.***> escribió:

> Gracias Yazna,
>
> Ya actualizé nuestro ambiente y el resultado y ahora creo que el  
> resultado esta perfecto.
>
> Voy cerrar este issue y cualquier comentario adicional del equipo de  
> contenido la aviso.
>
> Gracias
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/bireme/decs-api/issues/15#issuecomment-1448609708
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>




--
Este mensaje le ha llegado mediante el servicio de correo electronico que ofrece Infomed para respaldar el cumplimiento de las misiones del Sistema Nacional de Salud. La persona que envia este correo asume el compromiso de usar el servicio a tales fines y cumplir con las regulaciones establecidas

Infomed: http://www.sld.cu/
