### ISSUE TITLE
Implementar la opción de truncar

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/decs-api#16]
Yazna,

Conforme verificado la API actual permite el uso del simbolo de truncar $ para en words or bool:

https://decs.bvsalud.org/cgi-bin/mx/cgi=@vmx/decs?words=malar$&lang=en

https://decs.bvsalud.org/cgi-bin/mx/cgi=@vmx/decs?bool=107+malar$&lang=en

Podrias verificar la implementación deste recurso en la nueva API y considerar los simbolos $ y * para truncar?

Gracias

**Comment by yaznagv** [comment]
Agregada funcionalidad de busqueda con wildcards '*' y '$' en API de Busqueda (words, bool 1##) y API de busqueda rapida

**Comment by viniciusandrade** [comment]
Gracias @yaznagv codigo incorporado en ambiente de producción.
